### PR TITLE
Support of Admin5

### PR DESCRIPTION
**Pull request by GermanBluefox**
This will fix https://github.com/nisiode/ioBroker.iogo/issues/36

### CODE REVIEW

**Comment by Apollon77** [comment]
@nisiode when do you plan to release? please add info when done in https://github.com/ioBroker/ioBroker.admin/issues/936 please

**Comment by nisiode** [comment]
> @nisiode when do you plan to release? please add info when done in [ioBroker/ioBroker.admin#936](https://github.com/ioBroker/ioBroker.admin/issues/936) please

can do today
any guidance available for the deploy-step in the new GitHub actions?!?

**Comment by Apollon77** [comment]
>  any guidance available for the deploy-step in the new GitHub actions?!?
first of all optional, but honestly I find it very convenient, especially with the also added Releae script from AlCalzone

https://github.com/AlCalzone/release-script

in fact you only add changess to readme in a new section to mark as "work in progress". Then execute release script and tell if a patch, minor or major release. The script automatically takes the changelog content, increase all versions, add news to io-package.
also adds a tag with the verison and opushs that to github. tests run there and if successfull release is done automatically - you just need to add the needed NPM_TOKEN secret to your repo before

**Comment by nisiode** [comment]
thanks, will give it a try today

**Pull request merged**
